# Datasource - variables de entorno requeridas en el servidor
# MySQL (default):
#    SPRING_DATASOURCE_URL      = jdbc:mysql://localhost:3306/unicornt_store?useSSL=false&serverTimezone=America/Santiago&characterEncoding=UTF-8&useUnicode=true
#    # En caso de desplegar en docker y usar BD en el host, usar host.docker.internal en lugar de localhost:
#    SPRING_DATASOURCE_URL      = jdbc:mysql://host.docker.internal:3306/unicornt_store?useSSL=false&serverTimezone=America/Santiago&characterEncoding=UTF-8&useUnicode=true
#    SPRING_DATASOURCE_USERNAME = unicornt-store-admin
#    SPRING_DATASOURCE_PASSWORD = <password>
#
# PostgreSQL:
#    SPRING_DATASOURCE_URL      = jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?currentSchema=unicornt_store
#    SPRING_DATASOURCE_USERNAME = postgres.<supabaseid>
#    SPRING_DATASOURCE_PASSWORD = <password>
#    SPRING_DATASOURCE_HIKARI_CONNECTION_INIT_SQL = SET search_path TO unicornt_store, public
#    SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA = unicornt_store

# JPA - ddl-auto=update crea las tablas users, roles, users_roles automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Thymeleaf
spring.thymeleaf.cache=false

# Spring Boot
spring.application.name=unicornt-store
