# Postgres en Supabase
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.hikari.connection-init-sql=SET search_path TO unicornt_store, public
spring.jpa.properties.hibernate.default_schema=unicornt_store